---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      gomod:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      actions:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      docker:
        update-types:
          - "patch"
          - "minor"
