linters:
  enable:
    - asciicheck
    - depguard
    - errcheck
    - errorlint
    - gofmt
    - goimports
    - gosec
    - gocritic
    - importas
    - prealloc
    - revive
    - misspell
    - stylecheck
    - unconvert
    - unused
    - whitespace
output:
  uniq-by-line: false
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  issues-exit-code: 1
  timeout: 10m
