project_name: chart-testing
before:
  hooks:
    - go mod download
builds:
  - main: ct/main.go
    binary: ct
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - arm
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - >-
        -X github.com/helm/chart-testing/v3/ct/cmd.Version={{ .Tag }}
        -X github.com/helm/chart-testing/v3/ct/cmd.GitCommit={{ .Commit }}
        -X github.com/helm/chart-testing/v3/ct/cmd.BuildDate={{ .Date }}
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - etc/chart_schema.yaml
      - etc/lintconf.yaml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - ct
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
      - quay.io/helmpack/chart-testing:{{ .Tag }}
      - quay.io/helmpack/chart-testing:latest
    build_flag_templates:
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.description=ct - The chart testing tool
      - --label=org.opencontainers.image.vendor=Helm
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.source=https://github.com/helm/chart-testing
      - --label=org.opencontainers.image.authors=The Helm Authors
    extra_files:
      - etc/chart_schema.yaml
      - etc/lintconf.yaml
