project_name: chart-testing
builds:
  - main: app/main.go
    binary: ct
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - >-
        -X github.com/helm/chart-testing/app/cmd.Version={{ .Tag }}
        -X github.com/helm/chart-testing/app/cmd.GitCommit={{ .Commit }}
        -X github.com/helm/chart-testing/app/cmd.BuildDate={{ .Date }}
archive:
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - etc/chart_schema.yaml
    - etc/lintconf.yaml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - goos: linux
    goarch: amd64
    binary: ct
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
      - quay.io/helmpack/chart-testing:{{ .Tag }}
      - quay.io/helmpack/chart-testing:latest
    build_flag_templates:
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.description='ct - The chart testing tool'
      - --label=org.label-schema.vendor=Helm
    extra_files:
      - etc/chart_schema.yaml
      - etc/lintconf.yaml
