project_name: chart-testing
version: 2

env:
  - COSIGN_YES=true

before:
  hooks:
    - go mod download

sboms:
  - artifacts: archive

builds:
  - main: ct/main.go
    binary: ct
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - arm
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goarch: arm
        goos: windows
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - >-
        -X github.com/helm/chart-testing/v3/ct/cmd.Version={{ .Tag }}
        -X github.com/helm/chart-testing/v3/ct/cmd.GitCommit={{ .Commit }}
        -X github.com/helm/chart-testing/v3/ct/cmd.BuildDate={{ .Date }}

archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - etc/chart_schema.yaml
      - etc/lintconf.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

dockers_v2:
  - images:
      - "quay.io/helmpack/chart-testing"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .Commit }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.description": "ct - The chart testing tool"
      "org.opencontainers.image.vendor": "Helm"
      "org.opencontainers.image.licenses": "Apache-2.0"
      "org.opencontainers.image.source": "https://github.com/helm/chart-testing"
      "org.opencontainers.image.authors": "The Helm Authors"
    extra_files:
      - etc/chart_schema.yaml
      - etc/lintconf.yaml

signs:
  - id: all
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: all

docker_signs:
  - id: images
    cmd: cosign
    args: ["sign", "${artifact}"]

changelog:
  use: github-native
