
[[constraint]]
    name = "github.com/Masterminds/semver"
    version = "v1.4.2"

[[constraint]]
    name = "github.com/mitchellh/go-homedir"
    version = "v1.0.0"

[[constraint]]
    name = "github.com/pkg/errors"
    version = "v0.8.0"

[[constraint]]
    name = "github.com/spf13/cobra"
    version = "v0.0.3"

[[constraint]]
    name = "github.com/spf13/pflag"
    version = "v1.0.2"

[[constraint]]
    name = "github.com/spf13/viper"
    version = "v1.2.0"

[[constraint]]
    name = "github.com/stretchr/testify"
    version = "v1.2.2"

[[constraint]]
    name = "gopkg.in/yaml.v2"
    version = "v2.2.1"
