version: 2
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x test/e2e-kind.sh
  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v2.1.0
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add k8s https://github.com/your_git_repo/charts
            git fetch k8s master
            ct lint --config test/ct.yaml
  install-charts:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.1.0
      CHARTS_REPO: https://github.com/your_git_repo/charts
      K8S_VERSION: "v1.12.3"
    steps:
      - checkout
      - run:
          name: install
          command: |
            test/e2e-kind.sh
          no_output_timeout: 3600
workflows:
  version: 2
  lint_and_install:
    jobs:
      - lint-scripts
      - lint-charts:
          requires:
            - lint-scripts
      - install-charts:
          requires:
            - lint-charts
