# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

core:
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
  securityContext: {}

podSecurityContext: {}

nameOverride: ""
fullnameOverride: ""
