name: "Pull Request Size Labeler"
on: [pull_request]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: julrocas/pr-size-labeler@v1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/pr-size-labeler.yml
